# Generated by Django 5.1 on 2024-08-12 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_review_stars_alter_director_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='stars',
        ),
    ]
